language: node_js
node_js: 
  - 14


script: 
  - eslint 'src/**'
  # - npm run test:coveralls


jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage