version: '3.1'

services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_PASSWORD: Arthuracs2228@tt71
      POSTGRES_USER: shorAcs1
      POSTGRES_DB: 'nlw'
    volumes: 
      - ./src/infra/repository/postgres/migrations/2-create-users.sql:/docker-entrypoint-initdb.d/2-create-users.sql
      - ./src/infra/repository/postgres/migrations/3-create-tags.sql:/docker-entrypoint-initdb.d/3-create-tags.sql
    ports:
      - '8080:5432'  

   
   